In [4]:
import numpy as np


In [5]:
a=np.array([12,3.6,9,5.8,35])
print(a)

[12.   3.6  9.   5.8 35. ]


In [6]:
a.dtype

dtype('float64')

In [7]:
a=np.array([3,4,5,8])   # here a is user defined array object
print(a)

[3 4 5 8]


In [10]:
print(type(a))   #to display type of array object then use type() nd means no. of dimensional
print(a.ndim)     # to show no. of dimension of array object a

<class 'numpy.ndarray'>
1


In [12]:
print(a.dtype)    # to display datatype

int32


In [14]:
a.shape   # here 4 is no. of coulomns (row,coulomns)

(4,)

In [16]:
a.size    # to display the size of eachh element in bytes


4

In [17]:
a.nbytes
b=np.array([3,4,5,6,6])
print(b)
print(b.dtype)
print(b.size)


[3 4 5 6 6]
int32
5


In [19]:
a=np.array([34,6.8,98.4,28,89],int)
print(a)

[34  6 98 28 89]


In [21]:
a.dtype

dtype('int32')

In [24]:
# to retrieve value from particular index from single dimensional array
print(a)

[34  6 98 28 89]


In [26]:
# to retrieve value of 2nd location menas indexing
print(a[2])

98


In [29]:
print(a[1:4])

#  -----end of single dimensional array------>

[ 6 98 28]


In [30]:
# ---- start of multidimensional array
# to create a multidimensional array

In [36]:
x=np.array([[2,3,4,5],[12,45,78,98],[23,43,5,4]])


In [37]:
x

array([[ 2,  3,  4,  5],
       [12, 45, 78, 98],
       [23, 43,  5,  4]])

In [40]:
x.shape


(3, 4)

In [41]:
x.size     # how many elements in array

12

In [43]:
x.dtype

dtype('int32')

In [45]:
x.ndim

2

In [47]:
x.nbytes

48

In [49]:
type(x)

numpy.ndarray

In [55]:
x[0,3]    # to retrieve value from 0th row and 3rd calum   [row,column]--[start:stope:step]
x[0][3]    # same as first

5

In [60]:
x[:2,1:3]

array([[ 3,  4],
       [45, 78]])

In [63]:
b=np.arange(10)      # to generate array from anothe way using arange in numpy
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [64]:
b=np.arange(1,20,2)      # to gererate odd series start=1 and stop =19 step =+2
print(b)

[ 1  3  5  7  9 11 13 15 17 19]
